name: XCUI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.2_beta.app/Contents/Developer

jobs:
  build:
    name: Build and Test Komet on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild build-for-testing -target 'KometUITests' -scheme Komet
      - name: Test
        run: |
          xcodebuild test-without-building -target 'KometUITests' -scheme Komet
